version: "3.9"
services:
  app:
    image: docker
    environment:
      POSTGRES_USER: jp
      POSTGRES_PASSWD: 123456
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:14.5-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
